name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    # Add these two lines right here:
    defaults:
      run:
        working-directory: ./IISER_RESEARCH 

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.10'
        activate-environment: base
        environment-file: ./IISER_RESEARCH/environment.yml

    # 3. Lint with flake8
    - name: Lint with flake8
      shell: bash -l {0} # This forces the step to execute inside the activated Conda environment
      run: |
        conda install -y flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # 4. Test with pytest
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        conda install -y pytest
        pytest